@url = http://localhost:3000

### 登陆
POST {{url}}/admin/login
Content-Type: application/json

{
    "username":"lianglongfen",
    "password":"123456"
}

### 删除banner
GET {{url}}/banner/delete?id=1
Authorization: sss

### 删除teacher
GET {{url}}/teacher/delete?id=40bff310-636c-11e9-bfc4-ffc83613e3d1
Authorization: sss



